### ISSUE TITLE
Failed to deploy activityservice-0 pod.

### ISSUE THREAD

**Issue by minsikl** [lagom/activator-lagom-java-chirper#109]
I build docker images using the following command.
```
mvn clean package docker:build
```
I got errors when I deployed activityservice pods as follows:
```
# kubectl get pods
NAME                READY     STATUS             RESTARTS   AGE
activityservice-0   0/1       CrashLoopBackOff   25         1h
cassandra-0         1/1       Running            0          1h
chirpservice-0      1/1       Running            0          1h
friendservice-0     1/1       Running            0          1h
web-0               1/1       Running            0          1h
```

```
# kubectl log activityservice-0
2018-02-06T03:33:03.501Z [warn] application [] - env variables: play.crypto.secret is deprecated, use play.http.secret.key instead
2018-02-06T03:33:03.587Z [warn] akka.actor.ActorSystemImpl [sourceThread=main, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application, akkaTimestamp=03:33:03.579UTC] - CircuitBreakers is deprecated, use CircuitBreakersPanel instead. This warning is probably caused by your service locator. If you are using a 3rd party service locator, upgrade your dependencies, otherwise this service locator could become incompatible with Lagom in future versions.
2018-02-06T03:33:03.726Z [info] akka.io.AsyncDnsResolver [sourceThread=application-akka.actor.default-dispatcher-16, akkaSource=akka.tcp://application@172.30.71.160:2552/system/IO-DNS/async-dns/$a, sourceActorSystem=application, akkaTimestamp=03:33:03.723UTC] - Using the following DNS nameservers: /172.21.0.10:53
2018-02-06T03:33:04.472Z [error] com.lightbend.lagom.internal.javadsl.persistence.cassandra.CassandraPersistentEntityRegistry [sourceThread=main, akkaSource=CassandraPersistentEntityRegistry, sourceActorSystem=application, akkaTimestamp=03:33:04.453UTC] - Configuration for [cassandra-journal.keyspace] must be set in application.conf
2018-02-06T03:33:04.475Z [error] com.lightbend.lagom.internal.javadsl.persistence.cassandra.CassandraPersistentEntityRegistry [sourceThread=main, akkaTimestamp=03:33:04.454UTC, akkaSource=CassandraPersistentEntityRegistry, sourceActorSystem=application] - Configuration for [cassandra-snapshot-store.keyspace] must be set in application.conf
2018-02-06T03:33:04.524Z [error] akka.actor.ActorSystemImpl [sourceThread=main, akkaTimestamp=03:33:04.520UTC, akkaSource=akka.actor.ActorSystemImpl(application), sourceActorSystem=application] - Failed to initialize CassandraReadJournal
com.typesafe.config.ConfigException$Null: play/reference-overrides.conf @ jar:file:/maven/lagom-persistence-cassandra-core_2.12-1.4.0.jar!/play/reference-overrides.conf: 36: Configuration key 'keyspace' is set to null but expected STRING
	at com.typesafe.config.impl.SimpleConfig.throwIfNull(SimpleConfig.java:142)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at akka.persistence.cassandra.CassandraPluginConfig.<init>(CassandraPluginConfig.scala:33)
	at akka.persistence.cassandra.journal.CassandraJournalConfig.<init>(CassandraJournalConfig.scala:15)
	at akka.persistence.cassandra.query.scaladsl.CassandraReadJournal.<init>(CassandraReadJournal.scala:91)
	at akka.persistence.cassandra.query.CassandraReadJournalProvider.liftedTree1$1(CassandraReadJournalProvider.scala:16)
	at akka.persistence.cassandra.query.CassandraReadJournalProvider.<init>(CassandraReadJournalProvider.scala:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$createInstanceFor$1(ReflectiveDynamicAccess.scala:32)
	at scala.util.Try$.apply(Try.scala:209)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:27)
	at akka.persistence.query.PersistenceQuery.akka$persistence$query$PersistenceQuery$$instantiate$1(PersistenceQuery.scala:83)
	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$1.applyOrElse(PersistenceQuery.scala:88)
	at akka.persistence.query.PersistenceQuery$$anonfun$akka$persistence$query$PersistenceQuery$$createPlugin$1.applyOrElse(PersistenceQuery.scala:87)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recoverWith(Try.scala:232)
	at akka.persistence.query.PersistenceQuery.akka$persistence$query$PersistenceQuery$$createPlugin(PersistenceQuery.scala:87)
	at akka.persistence.query.PersistenceQuery$$anon$1.createExtension(PersistenceQuery.scala:64)
	at akka.persistence.query.PersistenceQuery$$anon$1.createExtension(PersistenceQuery.scala:62)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:881)
	at akka.actor.ExtensionId.apply(Extension.scala:78)
	at akka.actor.ExtensionId.apply$(Extension.scala:77)
	at akka.persistence.query.PersistenceQuery$$anon$1.apply(PersistenceQuery.scala:62)
	at akka.persistence.query.PersistenceQuery.readJournalPluginFor(PersistenceQuery.scala:60)
	at akka.persistence.query.PersistenceQuery.readJournalFor(PersistenceQuery.scala:46)
	at com.lightbend.lagom.internal.javadsl.persistence.cassandra.CassandraPersistentEntityRegistry.<init>(CassandraPersistentEntityRegistry.scala:31)
	at com.lightbend.lagom.internal.javadsl.persistence.cassandra.CassandraPersistentEntityRegistry$$FastClassByGuice$$296a63d0.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:51)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
...
```

**Comment by TimMoore** [comment]
See https://github.com/lagom/lagom-java-maven-chirper-example instead, which uses a different approach
