### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by huntc** [lagom/activator-lagom-java-chirper#2]
When trying to run tests:

```
2016-03-16 16:45:02,441 ERROR org.apache.cassandra.service.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[error] Test sample.chirper.friend.impl.FriendServiceTest.shouldBeAbleToCreateUsersAndConnectFriends failed: com.google.inject.CreationException: Unable to create injector, see the following errors:
[error] 
[error] 1) A binding to com.lightbend.lagom.javadsl.api.ServiceLocator was already configured at com.lightbend.lagom.javadsl.testkit.ServiceTest$.startServer(ServiceTest.scala:188):
[error] Binding(interface com.lightbend.lagom.javadsl.api.ServiceLocator to ConstructionTarget(class com.lightbend.lagom.internal.testkit.TestServiceLocator)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
[error]   at com.lightbend.lagom.internal.registry.ServiceRegistryModule.configure(ServiceRegistryModule.scala:43) (via modules: com.google.inject.util.Modules$OverrideModule -> com.lightbend.lagom.internal.registry.ServiceRegistryModule)
[error] 
[error] 1 error, took 8.57 sec
[error]     at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
[error]     at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
[error]     at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
[error]     at com.google.inject.Guice.createInjector(Guice.java:96)
[error]     at com.google.inject.Guice.createInjector(Guice.java:84)
[error]     at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
[error]     at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:208)
[error]     at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:127)
[error]     at com.lightbend.lagom.javadsl.testkit.ServiceTest$.startServer(ServiceTest.scala:210)
[error]     at com.lightbend.lagom.javadsl.testkit.ServiceTest$.withServer(ServiceTest.scala:160)
[error]     at com.lightbend.lagom.javadsl.testkit.ServiceTest.withServer(ServiceTest.scala)
[error]     at sample.chirper.friend.impl.FriendServiceTest.shouldBeAbleToCreateUsersAndConnectFriends(FriendServiceTest.java:24)
[error]     ...
```

**Comment by huntc** [comment]
Closing - duplication of https://github.com/lagom/lagom/issues/42
