### ISSUE TITLE
Running runAll doesnt work

### ISSUE THREAD

**Issue by ghost** [lagom/activator-lagom-java-chirper#5]
fresh code, running

```
sbt
runAll
```

from root of project gives error:

com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to com.lightbend.lagom.javadsl.api.ServiceLocator was already configured at com.typesafe.conductr.bundlelib.lagom.ServiceLocatorModule.bindings(ServiceLocatorModule.scala:16):
Binding(interface com.lightbend.lagom.javadsl.api.ServiceLocator to ConstructionTarget(class com.typesafe.conductr.bundlelib.lagom.ConductRServiceLocator) in interface javax.inject.Singleton) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1).
  at com.lightbend.lagom.internal.registry.ServiceRegistryModule.configure(ServiceRegistryModule.scala:31) (via modules: com.google.inject.util.Modules$OverrideModule -> com.lightbend.lagom.internal.registry.ServiceRegistryModule)

1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:84)
    at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
    at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
    at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
    at com.typesafe.conductr.bundlelib.lagom.ConductRApplicationLoader.load(ConductRApplicationLoader.scala:22)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1$$anonfun$2$$anonfun$3.apply(LagomReloadableDevServerStart.scala:151)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1$$anonfun$2$$anonfun$3.apply(LagomReloadableDevServerStart.scala:148)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1$$anonfun$2.apply(LagomReloadableDevServerStart.scala:148)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1$$anonfun$2.apply(LagomReloadableDevServerStart.scala:124)
    at scala.Option.map(Option.scala:146)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1.apply(LagomReloadableDevServerStart.scala:124)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1$$anonfun$apply$1.apply(LagomReloadableDevServerStart.scala:122)
    at scala.util.Success.flatMap(Try.scala:231)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1.apply(LagomReloadableDevServerStart.scala:122)
    at play.core.server.LagomReloadableDevServerStart$$anonfun$mainDev$1$$anon$2$$anonfun$get$1.apply(LagomReloadableDevServerStart.scala:114)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

page http://localhost:9000/ gives 
'Action Not Found' banner

**Comment by dotta** [comment]
@michalkarolik Thanks a lot for reporting the problem! It should be all good now.

**Comment by ghost** [comment]
@dotta thanks for fast fix! :) runAll now seems to run smoothly:

[info] Service chirp-impl listening for HTTP on 0:0:0:0:0:0:0:0:23966
[info] Service activity-stream-impl listening for HTTP on 0:0:0:0:0:0:0:0:27462
[info] Service load-test-impl listening for HTTP on 0:0:0:0:0:0:0:0:21360
[info] Service friend-impl listening for HTTP on 0:0:0:0:0:0:0:0:21998
[info] Service front-end listening for HTTP on 0:0:0:0:0:0:0:0:28118
[info](Services started, use Ctrl+D to stop and go back to the console...)

but after hitting localhost:9000 and waiting about 2 minutes ( browser loading page ) I get:

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "friend-impl-application-lagom.persistence.dispatcher-28"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "friend-impl-application-lagom.persistence.dispatcher-42"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "friend-impl-application-lagom.persistence.dispatcher-30"

and so on.

are there any recommended tweaks for jvm opts to run it?

**Comment by dotta** [comment]
@michalkarolik We actually have a ticket for this issue, see https://github.com/lagom/lagom/issues/32 if you want to track updates.

Are you running `sbt` or `activator`. I'm asking because I haven't hit the issue when using `sbt`, but I did see it when using `activator`. If stock sbt gives you the same problem, try the following java opts:

```
export JAVA_OPTS="-Xmx2g -XX:MaxMetaspaceSize=1g -Xss4m"
```

**Comment by ghost** [comment]
@dotta it works on stock sbt, thank you.
