### ISSUE TITLE
Jackson error after last update

### ISSUE THREAD

**Issue by amusaku** [lagom/activator-lagom-java-chirper#87]
18:05:39.306 [error] akka.actor.OneForOneStrategy [sourceThread=chirp-impl-application-akka.actor.default-dispatcher-18, akkaTimestamp=16:05:33.253UTC, akkaSource=akka://chirp-impl-application/system/sharding/ChirpRepositoryImpl%24ChirpTimelineEventReadSideProcessor/sample.chirper.chirp.impl.ChirpTimelineEvent1/sample.chirper.chirp.impl.ChirpTimelineEvent1/processor, sourceActorSystem=chirp-impl-application] - Instantiation of [simple type, class sample.chirper.chirp.api.Chirp] value failed (java.lang.NullPointerException): userId
 at [Source: [B@37c435c3; line: 1, column: 123]
com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class sample.chirper.chirp.api.Chirp] value failed (java.lang.NullPointerException): userId
 at [Source: [B@37c435c3; line: 1, column: 123]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:263)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:445)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:464)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:258)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:444)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:168)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1119)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
        at com.lightbend.lagom.internal.jackson.JacksonJsonSerializer.fromBinary(JacksonJsonSerializer.scala:131)
        at akka.serialization.Serialization.akka$serialization$Serialization$$deserializeByteArray(Serialization.scala:153)
        at akka.serialization.Serialization$$anonfun$deserialize$2.apply(Serialization.scala:142)
        at scala.util.Try$.apply(Try.scala:192)
        at akka.serialization.Serialization.deserialize(Serialization.scala:136)
        at akka.persistence.cassandra.journal.CassandraJournal$.deserializeEvent(CassandraJournal.scala:435)
        at akka.persistence.cassandra.query.EventsByTagFetcher.toPersistentRepr(EventsByTagFetcher.scala:183)
        at akka.persistence.cassandra.query.EventsByTagFetcher.loop$1(EventsByTagFetcher.scala:132)
        at akka.persistence.cassandra.query.EventsByTagFetcher.continue(EventsByTagFetcher.scala:174)
        at akka.persistence.cassandra.query.EventsByTagFetcher$$anonfun$receive$1.applyOrElse(EventsByTagFetcher.scala:86)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
        at akka.persistence.cassandra.query.EventsByTagFetcher.aroundReceive(EventsByTagFetcher.scala:43)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: userId
        at java.util.Objects.requireNonNull(Objects.java:228)
        at sample.chirper.chirp.api.Chirp.<init>(Chirp.java:40)
        at sample.chirper.chirp.api.Chirp.<init>(Chirp.java:31)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:256)
        ... 30 common frames omitted

**Comment by TimMoore** [comment]
@amusaku do you still have this problem in the latest version?

If so, please provide more details. How are you running the project? What action triggers the error?

**Comment by TimMoore** [comment]
I'll close this now, but if you'd like us to take another look, please comment again with more details and we can reopen.
